#!/usr/bin/env bash -eux
pfexec pkg install apache-24

pfexec mv /etc/opt/ooce/apache-2.4/httpd.conf /etc/opt/ooce/apache-2.4/httpd.conf.old
pfexec mv /home/admin/provisioners/conf/httpd.conf /etc/opt/ooce/apache-2.4/httpd.conf

pfexec svcadm enable svc:/network/http:apache24

echo "[OK] Apache service enabled."
