#!/usr/bin/env bash -eux
# Use the first disk not assigned to a zpool already to create the data pool.
for DISK in $(diskinfo -H | awk '{ print $2 }')
do
  echo "Checking ${DISK}"
  if [[ -z $(zpool list -H -v | egrep -e '^[[:blank:]]*'"${DISK}") ]]
  then
    echo "Found ${DISK}"
    echo "[II] Adding data zpool using whole disk ${DISK}"
    pfexec zpool create -f tank ${DISK}
    break
  fi
done

pfexec zfs create -o mountpoint=/export tank/export
pfexec zfs create tank/export/pkg
pfexec chown pkg5srv /export/pkg
pfexec zfs create -o mountpoint=/build tank/build
pfexec chown -R admin:staff /build

echo "[II] zfs provisioning completed!"
